### readme

GET http://localhost:3000/movies


### recupere un film por id
GET http://localhost:3000/movies/b6e03689-cccd-478e-8565-d92f40813b13

### crea un nuevo film por un genero
GET http://localhost:3000/movies?genre=Sci-Fi

### crea un nuevo film por POST
POST http://localhost:3000/movies
Content-Type: application/json

{
    
    "title":"The Whale",
    "year":2023,
    "director" : "Tommy Wirkola",
    "duration": 120,
    "poster": "https://www.imdb.com/title/tt8633478/mediaviewer/rm3873618944",
    "genre": ["Drama", "Sci-Fi"]


  }


### borra un film por id
DELETE http://localhost:3000/movies/aa4ce05e-2b5d-4151-9ed2-3225265d33f7
### actualiza un film por id
PATCH http://localhost:3000/movies/aa4ce05e-2b5d-4151-9ed2-3225265d33f7
Content-Type: application/json

{
  "title": "Run",
  "year": 2020,
  "director": "Aneesh Chaganty",
  "duration": 90,
  "genre": ["Horror", "Mystery", "Thriller"]
}